/*
# Create supermarket management schema

1. New Tables
- `profiles`: authenticated user identity, display name, and application role (`admin` or `cashier`).
- `categories`: product groups with activation state.
- `products`: product catalog with unique SKU/barcode, price, stock, reorder level, and activation state.
- `stock_movements`: append-only audit history for stock additions, adjustments, and sale deductions.
- `sales`: completed invoices with cashier, totals, discount, payment method, and timestamp.
- `sale_items`: immutable product lines attached to completed sales.

2. Security
- Row level security is enabled on every table.
- Admins can manage catalog and stock; authenticated users can read active catalog items.
- Cashiers can create sales only through the validated `create_sale` function and can read their own completed sales.
- Completed sales and sale items have no delete policy.
- Profile roles are assigned at signup and cannot be edited from the browser after creation.

3. Business Rules
- SKU/barcode uniqueness is enforced by database constraints.
- Sale totals and sale prices are recomputed from current product data inside the database function.
- Stock is locked and checked inside the sale transaction before it is reduced.
- Invoice numbers are generated by a database sequence.
*/

CREATE SEQUENCE IF NOT EXISTS invoice_number_seq START 1001;

CREATE TABLE IF NOT EXISTS profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name text NOT NULL CHECK (char_length(trim(full_name)) BETWEEN 2 AND 80),
  role text NOT NULL DEFAULT 'cashier' CHECK (role IN ('admin', 'cashier')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS categories (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL CHECK (char_length(trim(name)) BETWEEN 2 AND 80),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS products (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  category_id uuid NOT NULL REFERENCES categories(id) ON DELETE RESTRICT,
  name text NOT NULL CHECK (char_length(trim(name)) BETWEEN 2 AND 120),
  sku text NOT NULL CHECK (char_length(trim(sku)) BETWEEN 2 AND 40),
  barcode text NOT NULL CHECK (char_length(trim(barcode)) BETWEEN 2 AND 80),
  price numeric(12,2) NOT NULL CHECK (price >= 0),
  stock integer NOT NULL DEFAULT 0 CHECK (stock >= 0),
  reorder_level integer NOT NULL DEFAULT 10 CHECK (reorder_level >= 0),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (sku),
  UNIQUE (barcode)
);

CREATE TABLE IF NOT EXISTS stock_movements (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  changed_by uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE RESTRICT,
  change_type text NOT NULL CHECK (change_type IN ('purchase', 'adjustment', 'sale')),
  quantity integer NOT NULL CHECK (quantity <> 0),
  note text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sales (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_number text NOT NULL UNIQUE,
  cashier_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE RESTRICT,
  subtotal numeric(12,2) NOT NULL CHECK (subtotal >= 0),
  discount numeric(12,2) NOT NULL DEFAULT 0 CHECK (discount >= 0),
  total numeric(12,2) NOT NULL CHECK (total >= 0),
  payment_method text NOT NULL CHECK (payment_method IN ('cash', 'card', 'mobile')),
  status text NOT NULL DEFAULT 'completed' CHECK (status = 'completed'),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sale_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sale_id uuid NOT NULL REFERENCES sales(id) ON DELETE RESTRICT,
  product_id uuid NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  product_name text NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  unit_price numeric(12,2) NOT NULL CHECK (unit_price >= 0),
  line_total numeric(12,2) NOT NULL CHECK (line_total >= 0)
);

CREATE INDEX IF NOT EXISTS products_category_id_idx ON products(category_id);
CREATE INDEX IF NOT EXISTS products_active_stock_idx ON products(is_active, stock);
CREATE INDEX IF NOT EXISTS stock_movements_product_id_idx ON stock_movements(product_id, created_at DESC);
CREATE INDEX IF NOT EXISTS sales_cashier_id_created_at_idx ON sales(cashier_id, created_at DESC);
CREATE INDEX IF NOT EXISTS sales_created_at_idx ON sales(created_at DESC);
CREATE INDEX IF NOT EXISTS sale_items_sale_id_idx ON sale_items(sale_id);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE sale_items ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION is_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin');
$$;
REVOKE ALL ON FUNCTION is_admin() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION is_admin() TO authenticated;

DROP POLICY IF EXISTS "profiles_select_own" ON profiles;
CREATE POLICY "profiles_select_own" ON profiles FOR SELECT TO authenticated USING (id = auth.uid());
DROP POLICY IF EXISTS "profiles_insert_own" ON profiles;
CREATE POLICY "profiles_insert_own" ON profiles FOR INSERT TO authenticated WITH CHECK (id = auth.uid());

DROP POLICY IF EXISTS "categories_select_authenticated" ON categories;
CREATE POLICY "categories_select_authenticated" ON categories FOR SELECT TO authenticated USING (is_active OR is_admin());
DROP POLICY IF EXISTS "categories_insert_admin" ON categories;
CREATE POLICY "categories_insert_admin" ON categories FOR INSERT TO authenticated WITH CHECK (is_admin());
DROP POLICY IF EXISTS "categories_update_admin" ON categories;
CREATE POLICY "categories_update_admin" ON categories FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
DROP POLICY IF EXISTS "categories_delete_admin" ON categories;
CREATE POLICY "categories_delete_admin" ON categories FOR DELETE TO authenticated USING (is_admin());

DROP POLICY IF EXISTS "products_select_authenticated" ON products;
CREATE POLICY "products_select_authenticated" ON products FOR SELECT TO authenticated USING (is_active OR is_admin());
DROP POLICY IF EXISTS "products_insert_admin" ON products;
CREATE POLICY "products_insert_admin" ON products FOR INSERT TO authenticated WITH CHECK (is_admin());
DROP POLICY IF EXISTS "products_update_admin" ON products;
CREATE POLICY "products_update_admin" ON products FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
DROP POLICY IF EXISTS "products_delete_admin" ON products;
CREATE POLICY "products_delete_admin" ON products FOR DELETE TO authenticated USING (is_admin());

DROP POLICY IF EXISTS "stock_movements_select_admin" ON stock_movements;
CREATE POLICY "stock_movements_select_admin" ON stock_movements FOR SELECT TO authenticated USING (is_admin());
DROP POLICY IF EXISTS "stock_movements_insert_admin" ON stock_movements;
CREATE POLICY "stock_movements_insert_admin" ON stock_movements FOR INSERT TO authenticated WITH CHECK (is_admin() AND changed_by = auth.uid());

DROP POLICY IF EXISTS "sales_select_owner_or_admin" ON sales;
CREATE POLICY "sales_select_owner_or_admin" ON sales FOR SELECT TO authenticated USING (cashier_id = auth.uid() OR is_admin());
DROP POLICY IF EXISTS "sale_items_select_owner_or_admin" ON sale_items;
CREATE POLICY "sale_items_select_owner_or_admin" ON sale_items FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM sales WHERE sales.id = sale_items.sale_id AND (sales.cashier_id = auth.uid() OR is_admin())));

CREATE OR REPLACE FUNCTION create_sale(
  p_items jsonb,
  p_discount numeric DEFAULT 0,
  p_payment_method text DEFAULT 'cash'
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_sale_id uuid;
  v_subtotal numeric(12,2) := 0;
  v_discount numeric(12,2);
  v_total numeric(12,2);
  v_item jsonb;
  v_product products%ROWTYPE;
  v_quantity integer;
  v_line_total numeric(12,2);
  v_invoice text;
BEGIN
  IF auth.uid() IS NULL OR NOT EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('admin', 'cashier')) THEN
    RAISE EXCEPTION 'Not authorized';
  END IF;
  IF jsonb_typeof(p_items) <> 'array' OR jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION 'Cart is empty';
  END IF;
  IF p_payment_method NOT IN ('cash', 'card', 'mobile') THEN
    RAISE EXCEPTION 'Invalid payment method';
  END IF;
  v_discount := round(COALESCE(p_discount, 0), 2);
  IF v_discount < 0 OR v_discount > 100000 THEN
    RAISE EXCEPTION 'Invalid discount';
  END IF;

  FOR v_item IN SELECT value FROM jsonb_array_elements(p_items)
  LOOP
    v_quantity := (v_item->>'quantity')::integer;
    IF v_quantity IS NULL OR v_quantity < 1 OR v_quantity > 1000 THEN
      RAISE EXCEPTION 'Invalid quantity';
    END IF;
    SELECT * INTO v_product FROM products WHERE id = (v_item->>'product_id')::uuid AND is_active = true FOR UPDATE;
    IF NOT FOUND THEN
      RAISE EXCEPTION 'Product unavailable';
    END IF;
    IF v_product.stock < v_quantity THEN
      RAISE EXCEPTION 'Insufficient stock';
    END IF;
    v_line_total := round(v_product.price * v_quantity, 2);
    v_subtotal := v_subtotal + v_line_total;
  END LOOP;

  IF v_discount > v_subtotal THEN
    v_discount := v_subtotal;
  END IF;
  v_total := round(v_subtotal - v_discount, 2);
  v_invoice := 'INV-' || to_char(now(), 'YYYYMMDD') || '-' || nextval('invoice_number_seq');

  INSERT INTO sales (invoice_number, subtotal, discount, total, payment_method)
  VALUES (v_invoice, v_subtotal, v_discount, v_total, p_payment_method)
  RETURNING id INTO v_sale_id;

  FOR v_item IN SELECT value FROM jsonb_array_elements(p_items)
  LOOP
    v_quantity := (v_item->>'quantity')::integer;
    SELECT * INTO v_product FROM products WHERE id = (v_item->>'product_id')::uuid FOR UPDATE;
    v_line_total := round(v_product.price * v_quantity, 2);
    INSERT INTO sale_items (sale_id, product_id, product_name, quantity, unit_price, line_total)
    VALUES (v_sale_id, v_product.id, v_product.name, v_quantity, v_product.price, v_line_total);
    UPDATE products SET stock = stock - v_quantity, updated_at = now() WHERE id = v_product.id;
    INSERT INTO stock_movements (product_id, change_type, quantity, note)
    VALUES (v_product.id, 'sale', -v_quantity, v_invoice);
  END LOOP;
  RETURN v_sale_id;
END;
$$;
REVOKE ALL ON FUNCTION create_sale(jsonb, numeric, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION create_sale(jsonb, numeric, text) TO authenticated;

CREATE OR REPLACE FUNCTION adjust_product_stock(p_product_id uuid, p_quantity integer, p_change_type text, p_note text DEFAULT NULL)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_product products%ROWTYPE;
BEGIN
  IF NOT is_admin() THEN RAISE EXCEPTION 'Not authorized'; END IF;
  IF p_quantity = 0 OR p_quantity IS NULL OR p_change_type NOT IN ('purchase', 'adjustment') THEN RAISE EXCEPTION 'Invalid stock change'; END IF;
  SELECT * INTO v_product FROM products WHERE id = p_product_id FOR UPDATE;
  IF NOT FOUND OR v_product.stock + p_quantity < 0 THEN RAISE EXCEPTION 'Invalid stock change'; END IF;
  UPDATE products SET stock = stock + p_quantity, updated_at = now() WHERE id = p_product_id;
  INSERT INTO stock_movements (product_id, changed_by, change_type, quantity, note)
  VALUES (p_product_id, auth.uid(), p_change_type, p_quantity, NULLIF(trim(p_note), ''));
END;
$$;
REVOKE ALL ON FUNCTION adjust_product_stock(uuid, integer, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION adjust_product_stock(uuid, integer, text, text) TO authenticated;

GRANT USAGE ON SEQUENCE invoice_number_seq TO authenticated;
REVOKE INSERT, UPDATE, DELETE ON sales FROM authenticated;
REVOKE INSERT, UPDATE, DELETE ON sale_items FROM authenticated;
REVOKE UPDATE ON profiles FROM authenticated;
